##VARIABLE
@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@id = 61045492f997a47a057b04e3


###CREATE A STREAK
POST  http://{{host}}/streak HTTP/1.1
Content-Type: {{contentType}}

{
  "title" : "100 days of javascript",
  "days" : "100",
  "description" : "The motive is to cover the fundamantals",
}

####GET STREAKS
GET http://{{host}}/streak HTTP/1.1
Content-Type: {{contentType}}

###DELETE STREAK
DELETE http://{{host}}/streak/{{id}} HTTP/1.1
Content-Type: {{contentType}}

###UPDATE STREAK
PATCH  http://{{host}}/streak/{{id}} HTTP/1.1
Content-Type: {{contentType}}

{
  "title" : "10 days of javascript",
  "days" : "10",
  "description" : "The motive is to cover the fundamantals"
}


###CREATE STREAK DETAIL
POST  http://{{host}}/streakDetail HTTP/1.1
Content-Type: {{contentType}}

{
  "date" : "2021-08-01T00:00:00.000Z",
  "streakId" : "61045492f997a47a057b04e3",
  "rewards" : [],
  "reward" : false
}

####GET STREAK DETAIL
GET http://{{host}}/streakDetail/{{id}} HTTP/1.1
Content-Type: {{contentType}}


###UPDATE STREAK DETAIL
PATCH  http://{{host}}/streakDetail/{{id}} HTTP/1.1
Content-Type: {{contentType}}

{
  "date" : "1626458086485",
  "streakId" : "60f1ca55cf75426f325ad773",
  "rewards" : [],
  "reward" : false
}


###DELETE STREAK DETAIL
DELETE http://{{host}}/streakDetail/{{id}} HTTP/1.1
Content-Type: {{contentType}}


###CREATE REWARD
POST  http://{{host}}/reward HTTP/1.1
Content-Type: {{contentType}}

{
  "title" : "Buy Monitor",
  "streakId" : "60f1ca55cf75426f325ad773",
  "date" : "1626458086485"
}

####GET REWARDS
GET http://{{host}}/reward HTTP/1.1
Content-Type: {{contentType}}


###UPDATE REWARD
PATCH  http://{{host}}/reward/{{id}} HTTP/1.1
Content-Type: {{contentType}}

{
  "title" : "Buy Monitor12",
  "streakId" : "60f1ca55cf75426f325ad773",
  "date" : "1626458086485"
}

###DELETE REWARD
DELETE http://{{host}}/reward/{{id}} HTTP/1.1
Content-Type: {{contentType}}